apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "finops-operator-scraper-chart.fullname" . }}-repo-envvar-configmap-scraper-md2d926d4b
  labels:
  {{- include "finops-operator-scraper-chart.labels" . | nindent 4 }}
data:
  REPO: {{ .Values.repoEnvvarConfigmapScraperMd2D926D4B.repo | quote }}
