apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "finops-operator-scraper-chart.fullname" . }}-repo-envvar
  labels:
  {{- include "finops-operator-scraper-chart.labels" . | nindent 4 }}
data:
  REGISTRY: {{ .Values.env.REGISTRY | quote }}
  REGISTRY_CREDENTIALS: {{ .Values.env.REGISTRY_CREDENTIALS | quote }}
  URL_DB_WEBSERVICE: {{ .Values.env.URL_DB_WEBSERVICE | quote }}
