apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "finops-operator-scraper-chart.fullname" . }}-repo-envvar
  labels:
  {{- include "finops-operator-scraper-chart.labels" . | nindent 4 }}
data:
  REPO: {{ .Values.repoEnvvarConfigmapScraper.repo | quote }}
