apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "finops-operator-scraper-chart.fullname" . }}-manager
  labels:
  {{- include "finops-operator-scraper-chart.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: '{{ include "finops-operator-scraper-chart.fullname" . }}-manager'
subjects:
- kind: ServiceAccount
  name: {{ include "finops-operator-scraper-chart.serviceAccountName" . }}
  namespace: '{{ .Release.Namespace }}'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "finops-operator-scraper-chart.fullname" . }}-leader-election
  labels:
  {{- include "finops-operator-scraper-chart.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: '{{ include "finops-operator-scraper-chart.fullname" . }}-leader-election'
subjects:
- kind: ServiceAccount
  name: {{ include "finops-operator-scraper-chart.serviceAccountName" . }}
  namespace: '{{ .Release.Namespace }}'
