apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "finops-operator-scraper-chart.fullname" . }}-controller-manager
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: operator-scraper
    app.kubernetes.io/part-of: operator-scraper
  {{- include "finops-operator-scraper-chart.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.controllerManager.serviceAccount.annotations | nindent 4 }}